spring:
    application:
        name: employee-service


server:
    port: 8080
 
management:
  endpoints:
    web:
      exposure:
        include: health, refresh
  endpoint:
    health:
      enabled: true